const routePaths = {
  home: "/",
  solucoes: "/solucoes",
  bisinessIntelligence: "/business-intelligence",
  tributario: "/tributario",
  contabilidade: "/contabilidade",
  consultoriRh: "/consultoriaRH",
  cigam: "/cigam",
  consultoriaEmpresarial: "/consultoria-empresarial",
  holding: "/holding",
  treinamentos: "/treinamentos",
  cursos: "/cursos",
  modulosCigam: "/modulos-cigam",
  dashboardGestor: "/dashboard-contabilidade",
  dashboardFinanceiro: "/dashboard-financeiro",
  dashboardRH: "/dashboard-rh",
  dashboardGestaoEstoque: "/dashboard-gestao-estoque",
  dashboardTributario: "/dashboard-tributario",
  questionarioRH: "/questionario-rh",
  questionarioCigam: "/questionario-cigam",
  questionarioTributario: "/questionario-tributario",
  questionarioEmpresarial: "/questionario-empresarial",
  questionarioHolding: "/questionario-holding",
  questionarioBI: "/questionario-bi",
  adminlogin: "/login",

  adminManager: "/admin/gerenciamento",
  consultaCnpj: "/admin/consulta-cnpj",
  questionarioConsultoria: "/admin/questionario-consultoria",
  resultadoConsultoria: "/admin/resultado-consultoria",
  cadastroPergunta: "/admin/cadastro-pergunta",
  leadsCadastrados: "/admin/leads-cadastrados",
  listaPerguntas: "/admin/lista-perguntas",
  questionarioBusinessIntelligence: "/admin/questionario-business-intelligence",
  reenvioEmailLead: "/admin/reenvio-email-lead",
  reenvioEmailFalavinha: "/admin/reenvio-email-falavinha",
  respostasLeads: "/admin/respostas-leads",
  propostaLead: "/admin/proposta-lead",
};

export default routePaths;
